### ISSUE TITLE
Research tools for public-web rework

### ISSUE THREAD

**Issue by Afrokk** [CHIMEFRB/web-exploration#1]
For the `public-web` rework, we must research different tools and stacks to identify which one best suits our needs. 

### To-Do:
- [x] Explore/research about different design systems, tools and frameworks
- [x] Design a page with a React 19 Stack
- [x] Design a page with a Vue 3 Stack
- [x] Design a page with React 18 + Primer Design stack
- [x] Document findings

### Links:
[web-exploration/public-web-rework](https://github.com/CHIMEFRB/web-exploration/tree/main/Public%20Web%20Rework)
[web-exploration/public-web-vue](https://github.com/CHIMEFRB/web-exploration/tree/main/Public%20Web%20Rework/public-web-vue)
[web-exploration/public-web-react](https://github.com/CHIMEFRB/web-exploration/tree/main/Public%20Web%20Rework/public-web-react)
[web-exploration/public-web-react18-primer](https://github.com/CHIMEFRB/web-exploration/tree/main/Public%20Web%20Rework/public-web-react18)

### Findings:
[Readme](https://github.com/CHIMEFRB/web-exploration/blob/main/Public%20Web%20Rework/README.md)
[Vue Stack Readme](https://github.com/CHIMEFRB/web-exploration/blob/main/Public%20Web%20Rework/public-web-vue/README.md)
[React  Stack Readme](https://github.com/CHIMEFRB/web-exploration/blob/main/Public%20Web%20Rework/public-web-react/README.md)
[React v18 + Primer Stack Readme](https://github.com/CHIMEFRB/web-exploration/blob/main/Public%20Web%20Rework/public-web-react18/README.md)
